name: CI de Python con Pytest

on:
  push:
    branches:
      - main # O la rama principal que uses, por ejemplo, master

jobs:
  build:
    runs-on: ubuntu-latest # O windows-latest, macos-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.5'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest # Instala pytest

    - name: Ejecutar tests con Pytest
      run: |
        pytest # Ejecuta todos los tests en tu proyecto
